const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
let notices=[],categories=[],keywords=[],rules={},visualData={},priorityItems=[];let product='shirt';let selected={};let currentCategory='衬衫';let currentVisual='shirt';let currentReference='shirt';let currentPriority='shirt';
async function load(){
 const urls=['data/notices.json','data/category_guide.json','data/keyword_library.json','data/title_rules.json','data/visual_examples.json','data/priority.json'];
 const [n,c,k,r,v,p]=await Promise.all(urls.map(u=>fetch(u).then(x=>x.json())));
 notices=n.notices;categories=c.items;keywords=k.items;rules=r.rules;visualData=v;priorityItems=p.items||[];
 $('#today').textContent=new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'});
 renderNoticeStrip();renderCategories();renderTitle();renderVisual();renderReference();renderPriorityPreview();bind();
}
function bind(){
 $$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
 $$('.major-tab').forEach(b=>b.addEventListener('click',()=>{const group=b.parentElement.dataset.group;$$(`.major-tabs[data-group="${group}"] .major-tab`).forEach(x=>x.classList.remove('active'));b.classList.add('active');const value=b.dataset.value;if(group==='category'){currentCategory=value;renderCategories()}if(group==='title'){product=value;selected={};renderTitle()}if(group==='visual'){currentVisual=value;renderVisual()}if(group==='reference'){currentReference=value;renderReference()}}));
 $$('.priority-entry').forEach(b=>b.addEventListener('click',()=>{currentPriority=b.dataset.priorityLink;$$('.priority-entry').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPriorityPreview()}));
 document.addEventListener('click',e=>{const btn=e.target.closest('[data-copy]');if(btn){const id=btn.dataset.copy;const el=document.getElementById(id);copyText(el?el.innerText:btn.dataset.text,btn)}});
}
function go(id){$$('.page').forEach(p=>p.classList.remove('active'));const target=$('#'+id);if(target)target.classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'})}
function renderNoticeStrip(){const hot=notices.find(n=>n.type==='热搜词')||notices[0];const updates=notices.filter(n=>n.type!=='热搜词');const latest=updates[0]||notices[0];$('#hotNotice').textContent=hot?hot.title:'';$('#hotDate').textContent=hot?hot.date:'';$('#updateNotice').textContent=latest?`${latest.title} · ${latest.content}`:'';$('#updateDate').textContent=latest?latest.date:''}
function renderCategories(){const arr=categories.filter(x=>x.category===currentCategory);$('#categoryList').innerHTML=arr.length?arr.map((x,i)=>`<div class="path-item"><div class="path-top"><b>${x.tag}</b><span>${x.category} · ${x.season}</span></div><div class="path-text" id="path-${currentCategory}-${i}">${x.path}</div><button class="mini-copy" data-copy="path-${currentCategory}-${i}">一键复制</button></div>`).join(''):`<div class="empty-card"><b>暂无类目数据</b><span>请在 data/category_guide.json 中补充。</span></div>`}
const dimMap={target:'目标人群(Target)',category:'品类(Category)',pattern:'图案/花色(Pattern)',neckline:'领型(Neckline)',occasion:'场景(Occasion)',sleeve:'袖长(Sleeve)',style:'风格(Style)',material:'面料/材质(Material)',closure:'闭合方式(Closure)',color:'颜色(Color)',fit:'版型(Fit)'};
function getOptions(key){return keywords.filter(x=>x.key===key)}
function renderTitle(){const rule=rules[product];selected={};$('#titleRuleNote').textContent=rule.note;$('#dimensionForm').innerHTML=rule.order.map(key=>{const arr=getOptions(key);if(!arr.length)return '';let type=rule.required.includes(key)?'required':rule.high.includes(key)?'high':'extra';let badge=type==='required'?'必选维度':type==='high'?'高优补充':'额外拓展';return `<div class="dim-block"><div class="dim-head"><b>${dimMap[key]||key}</b><span class="dim-badge ${type}">${badge}</span></div><div class="options">${arr.slice(0,60).map(o=>`<button class="opt" data-key="${key}" data-idx="${o.id}">${o.zh}<br><small>${o.en}</small></button>`).join('')}</div></div>`}).join('');$$('#dimensionForm .opt').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.key,id=+b.dataset.idx;if(selected[key]===id){delete selected[key];b.classList.remove('selected')}else{$$(`#dimensionForm .opt[data-key="${key}"]`).forEach(x=>x.classList.remove('selected'));selected[key]=id;b.classList.add('selected')}updateResult()}));updateResult()}
function chosen(key){const id=selected[key];return keywords.find(x=>x.id===id)}
function updateResult(){const rule=rules[product];let zh=[],en=[];rule.order.forEach(k=>{const x=chosen(k);if(x){zh.push(x.zh);en.push((x.variants||x.en).split(',')[0].trim())}});$('#zhOutput').textContent=zh.length?zh.join(' '):'请选择词语';$('#enOutput').textContent=en.length?en.join(' '):'Select keywords';const done=rule.order.filter(k=>selected[k]).length;const req=rule.required.filter(k=>selected[k]).length;const score=Math.min(100,Math.round(25+done/rule.order.length*55+req/rule.required.length*20));$('#score').textContent=`${score} / 100`;$('#coverage').innerHTML=rule.order.map(k=>`<span class="${selected[k]?'ok':''}">${dimMap[k]} ${selected[k]?'✓':'未选'}</span>`).join('')}
function renderVisual(){if(currentVisual==='shirt'){const v=visualData.shirt;$('#visualContent').innerHTML=`<div class="visual-grid"><div class="visual-card"><img src="${v.sourceImage}" alt="${v.title}"></div><div class="prompt-card"><div class="tag">衬衫 · AI 改图指令</div><h3>保留商品，升级表达</h3><p id="visualPrompt">${v.prompt}</p><button class="primary full" data-copy="visualPrompt">复制 AI 指令</button><div class="checklist">${v.checklist.map(x=>`<div class="check">${x}</div>`).join('')}</div></div></div>`}else{$('#visualContent').innerHTML=`<div class="empty-card"><b>夹克外套视觉优化</b><span>当前第一版先配置衬衫示例。后续只需把夹克外套参考图和 AI 指令补充到 data/visual_examples.json，即可直接上线。</span></div>`}}
function renderReference(){if(currentReference==='jacket'){$('#referenceContent').innerHTML=`<div class="reference-stack"><div class="reference-block"><div class="reference-title"><b>都市基础风</b><span>夹克外套 · 款式参考</span></div><iframe src="assets/reference/jacket-urban-basic.pdf" title="都市基础风"></iframe><a class="reference-open" href="assets/reference/jacket-urban-basic.pdf" target="_blank">打开完整 PDF →</a></div><div class="reference-block"><div class="reference-title"><b>工装 / 军事类</b><span>夹克外套 · 款式参考</span></div><iframe src="assets/reference/jacket-workwear-military.pdf" title="工装军事类"></iframe><a class="reference-open" href="assets/reference/jacket-workwear-military.pdf" target="_blank">打开完整 PDF →</a></div></div>`}else{$('#referenceContent').innerHTML=`<div class="empty-card"><b>衬衫需求款式参考</b><span>当前上传资料中暂无独立的衬衫企划 PDF。后续将衬衫参考资料放入 assets/reference/，再在 script.js 中增加对应入口即可。</span></div>`}}
function sortedPriority(kind){return priorityItems.filter(x=>x.category===kind).sort((a,b)=>{const d=(b.addedAt||'').localeCompare(a.addedAt||'');if(d!==0)return d;return (b.sort||0)-(a.sort||0)})}
function renderPriorityPreview(){const label=currentPriority==='shirt'?'衬衫':'夹克外套';const list=sortedPriority(currentPriority);let html=`<div class="preview-head"><div><b>${label}重点款式预览</b><small class="update-count"> ${list.length} 张 · 最新更新优先</small></div><a href="priority.html#${currentPriority}">进入完整图片集合页 →</a></div><div class="preview-grid">`;html+=list.slice(0,10).map((x,i)=>`<button class="preview-item" data-lightbox="${x.image}"><img src="${x.image}" alt="${x.title}"><span>${x.title}${i<3?' · 最新':''}</span><em>${x.addedAt||''}</em></button>`).join('');html+='</div>';$('#priorityPreview').innerHTML=html;$$('[data-lightbox]').forEach(b=>b.addEventListener('click',()=>openLightbox(b.dataset.lightbox)))}
function openLightbox(src){let box=document.getElementById('lightbox');if(!box){box=document.createElement('div');box.id='lightbox';box.innerHTML='<div class="lightbox-backdrop"></div><button class="lightbox-close">×</button><img class="lightbox-img" alt="大图预览">';document.body.appendChild(box);box.querySelector('.lightbox-backdrop').addEventListener('click',()=>box.classList.remove('show'));box.querySelector('.lightbox-close').addEventListener('click',()=>box.classList.remove('show'))}box.querySelector('.lightbox-img').src=src;box.classList.add('show')}
async function copyText(text,btn){try{await navigator.clipboard.writeText(text);const old=btn.innerText;btn.innerText='已复制 ✓';setTimeout(()=>btn.innerText=old,1200)}catch(e){alert('复制失败，请手动复制。')}}
load();
