const $=(s)=>document.querySelector(s); const $$=(s)=>[...document.querySelectorAll(s)];
let notices=[], categories=[], keywords=[], rules={}, visualData={}; let product='shirt'; let selected={}; let noticeFilter='全部';
async function load(){
 const urls=['data/notices.json','data/category_guide.json','data/keyword_library.json','data/title_rules.json','data/visual_examples.json'];
 const [n,c,k,r,v]=await Promise.all(urls.map(u=>fetch(u).then(x=>x.json()))); notices=n.notices;categories=c.items;keywords=k.items;rules=r.rules;visualData=v;
 $('#today').textContent=new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}); renderNotices(); renderCategories(); renderTitle(); renderVisual(); renderPriority('shirt'); bind();
}
function bind(){
 $$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
 $$('.notice-tabs button').forEach(b=>b.addEventListener('click',()=>{noticeFilter=b.dataset.filter;renderNotices()}));
 $$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCategories(b.dataset.cat)}));
 $$('.product-tab').forEach(b=>b.addEventListener('click',()=>{product=b.dataset.product;$$('.product-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');selected={};renderTitle()}));
 $$('.platform').forEach(b=>b.addEventListener('click',()=>{$$('.platform').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
 $$('.priority-tab').forEach(b=>b.addEventListener('click',()=>{ $$('.priority-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPriority(b.dataset.priority)}));
 document.addEventListener('click',e=>{const btn=e.target.closest('[data-copy]'); if(btn){const id=btn.dataset.copy; const el=document.getElementById(id); copyText(el?el.innerText:btn.dataset.text,btn)}});
}
function go(id){$$('.page').forEach(p=>p.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function renderNotices(){const types=['全部','热搜词','备货相关通知','提报通知','其他通知'];$('#noticeTabs').innerHTML=types.map(x=>`<button data-filter="${x}" class="${noticeFilter===x?'active':''}">${x}</button>`).join('');$('#noticeList').innerHTML=notices.filter(n=>noticeFilter==='全部'||n.type===noticeFilter).slice(0,4).map(n=>`<article class="notice-item"><div class="meta"><span class="type ${n.level}">${n.type}</span><span>${n.date}</span></div><h4>${n.title}</h4><p>${n.content}</p></article>`).join(''); $$('#noticeTabs button').forEach(b=>b.addEventListener('click',()=>{noticeFilter=b.dataset.filter;renderNotices()}))}
function renderCategories(filter='全部'){const arr=filter==='全部'?categories:categories.filter(x=>x.category===filter);$('#categoryList').innerHTML=arr.map((x,i)=>`<div class="path-item"><div class="path-top"><b>${x.tag}</b><span>${x.category} · ${x.season}</span></div><div class="path-text" id="path-${i}">${x.path}</div><button class="mini-copy" data-copy="path-${i}">一键复制</button></div>`).join('')}
const dimMap={target:'目标人群(Target)',category:'品类(Category)',pattern:'图案/花色(Pattern)',neckline:'领型(Neckline)',occasion:'场景(Occasion)',sleeve:'袖长(Sleeve)',style:'风格(Style)',material:'面料/材质(Material)',closure:'闭合方式(Closure)',color:'颜色(Color)',fit:'版型(Fit)'};
function getOptions(key){return keywords.filter(x=>x.key===key)}
function renderTitle(){const rule=rules[product]; selected={}; $('#dimensionForm').innerHTML=rule.order.map(key=>{const arr=getOptions(key); if(!arr.length)return ''; let type=rule.required.includes(key)?'required':rule.high.includes(key)?'high':'extra';let badge=type==='required'?'必选维度':type==='high'?'高优补充':'额外拓展';return `<div class="dim-block"><div class="dim-head"><b>${dimMap[key]||key}</b><span class="dim-badge ${type}">${badge}</span></div><div class="options">${arr.slice(0,50).map((o,i)=>`<button class="opt" data-key="${key}" data-idx="${o.id}">${o.zh}<br><small>${o.en}</small></button>`).join('')}</div></div>`}).join(''); $$('#dimensionForm .opt').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.key;const id=+b.dataset.idx; if(selected[key]===id){delete selected[key];b.classList.remove('selected')}else{ $$('#dimensionForm .opt[data-key="'+key+'"]').forEach(x=>x.classList.remove('selected'));selected[key]=id;b.classList.add('selected')} updateResult() })); updateResult();}
function chosen(key){const id=selected[key];return keywords.find(x=>x.id===id)}
function updateResult(){const rule=rules[product];let zh=[],en=[];rule.order.forEach(k=>{const x=chosen(k);if(x){zh.push(x.zh);en.push((x.variants||x.en).split(',')[0].trim())}});if(product==='shirt'){zh=zh.length?zh.join(' '):'请选择词语';en=en.length?en.join(' '):'Select keywords'}else{zh=zh.length?zh.join(' '):'请选择词语';en=en.length?en.join(' '):'Select keywords'}$('#zhOutput').textContent=zh;$('#enOutput').textContent=en;const done=rule.order.filter(k=>selected[k]).length;const req=rule.required.filter(k=>selected[k]).length;const score=Math.min(100,Math.round(25+done/rule.order.length*55+req/rule.required.length*20));$('#score').textContent=`${score} / 100`;$('#coverage').innerHTML=rule.order.map(k=>`<span class="${selected[k]?'ok':''}">${dimMap[k]} ${selected[k]?'✓':'未选'}</span>`).join('')}
function renderVisual(){const v=visualData.shirt;$('#visualPrompt').textContent=v.prompt;$('#visualChecklist').innerHTML=v.checklist.map(x=>`<div class="check">${x}</div>`).join('')}
function renderPriority(which){const src=which==='shirt'?'assets/priority/shirt-priority.pdf':'assets/priority/jacket-priority.pdf';$('#priorityContent').innerHTML=`<iframe src="${src}"></iframe><div style="padding:10px 2px 0;color:#8b919a;font-size:11px">PDF 集合页 · 仅作款式方向参考，不可直接复制设计。</div>`}
async function copyText(text,btn){try{await navigator.clipboard.writeText(text);const old=btn.innerText;btn.innerText='已复制 ✓';setTimeout(()=>btn.innerText=old,1200)}catch(e){alert('复制失败，请手动复制。')}}
load();
